In [1]:

from scipy.optimize import fsolve

# Import pandas
import pandas as pd

# Import numpy
import numpy as np
from numpy import *
from numpy.linalg import multi_dot

# Plot settings
import matplotlib
import matplotlib.pyplot as plt
matplotlib.rcParams['figure.figsize'] = 16, 8

# Ignore warnings
import warnings
warnings.filterwarnings('ignore')

In [2]:
dataset = pd.read_excel("2021_PBO_CF.xlsx",sheet_name = "PBO Cashflows Summary", skiprows = [0,1,2], usecols=[0,1,2,3,4], na_values=[""],index_col=0)
#dataset.set_index('Year')
dataset

            Time    Retirement       Pension           IBT
Year
2021-12-31   0.5  1.204791e+09  2.626341e+08  4.239987e+08
2022-12-31   1.5  1.261684e+09  2.935988e+08  4.570359e+08
2023-12-31   2.5  1.322496e+09  3.253961e+08  4.883641e+08
2024-12-31   3.5  1.382473e+09  3.576365e+08  5.168109e+08
2025-12-31   4.5  1.441835e+09  3.898680e+08  5.408954e+08
...          ...           ...           ...           ...
2096-12-31  75.5  1.769334e+05  3.948190e+06  1.620103e+06
2097-12-31  76.5  1.503230e+05  2.959047e+06  1.183430e+06
2098-12-31  77.5  1.300395e+05  2.180928e+06  8.499443e+05
2099-12-31  78.5  1.152802e+05  1.579033e+06  5.996743e+05
2100-12-31  79.5  1.039848e+05  1.121814e+06  4.153039e+05

[80 rows x 4 columns]

In [3]:
Time = dataset['Time']
RP = dataset['Retirement']
DR = .03
len(Time)
RP[0]
len(Time)

80

In [4]:
# Initialize the lists
liabilityRP = np.zeros(len(Time))
for j in range (len(Time)):
        for i in range (j,len(Time)):
            liabilityRP[j] += ((RP[i]/((1+DR)**Time[i-j]))) 
liabilityRP

array([3.31275129e+10, 3.28986085e+10, 3.26050972e+10, 3.22410632e+10,
       3.18052386e+10, 3.12960932e+10, 3.07149243e+10, 3.00656014e+10,
       2.93548066e+10, 2.85864992e+10, 2.77638440e+10, 2.68916821e+10,
       2.59748818e+10, 2.50194173e+10, 2.40339447e+10, 2.30225078e+10,
       2.19917005e+10, 2.09468936e+10, 1.98929833e+10, 1.88340061e+10,
       1.77762604e+10, 1.67227888e+10, 1.56779334e+10, 1.46438459e+10,
       1.36265318e+10, 1.26308894e+10, 1.16601483e+10, 1.07191231e+10,
       9.81240781e+09, 8.94431320e+09, 8.12021134e+09, 7.34077906e+09,
       6.61139939e+09, 5.93244870e+09, 5.30330355e+09, 4.72428996e+09,
       4.19423141e+09, 3.71040060e+09, 3.27011680e+09, 2.87129852e+09,
       2.51125982e+09, 2.18743578e+09, 1.89732414e+09, 1.63846589e+09,
       1.40843244e+09, 1.20485464e+09, 1.02544599e+09, 8.68025492e+08,
       7.30539385e+08, 6.11056540e+08, 5.07771319e+08, 4.19001840e+08,
       3.43186097e+08, 2.78875544e+08, 2.24729029e+08, 1.79507207e+08,
       1.42068023e+08, 1.11362764e+08, 8.64336903e+07, 6.64112260e+07,
       5.05115426e+07, 3.80363529e+07, 2.83700872e+07, 2.09756449e+07,
       1.53930574e+07, 1.12339840e+07, 8.17387569e+06, 5.95012612e+06,
       4.34998765e+06, 3.20707914e+06, 2.39157651e+06, 1.80768974e+06,
       1.38364629e+06, 1.06854466e+06, 8.26883425e+05, 6.33901373e+05,
       4.73350635e+05, 3.34989982e+05, 2.13064013e+05, 1.02459278e+05])

In [5]:
liabilityRP = np.zeros(len(Time))
liabilityRP[0] += ((RP[0]/((1+DR)**Time[0-0]))) 
liabilityRP

array([1.1871163e+09, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
       0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00])

In [6]:
df=dataset.copy()

#set start date and end date
start_date = df.index.min() - pd.DateOffset(day=0)
end_date = df.index.max() + pd.DateOffset(day=31)

#create new dataframe monthly index
dates = pd.date_range(start_date, end_date, freq='M')
dates.name = 'date'

#reindex yearly dataframe to monthly dataframe
df = df.reindex(dates, method='ffill')

#export monthly dataframe to excel
filepath = 'monthly_data.xlsx'
writer = pd.ExcelWriter(filepath, engine='xlsxwriter')
df.to_excel(writer, sheet_name='data')
writer.save()


df.head(20)

            Time    Retirement       Pension           IBT
date
2021-12-31   0.5  1.204791e+09  2.626341e+08  4.239987e+08
2022-01-31   0.5  1.204791e+09  2.626341e+08  4.239987e+08
2022-02-28   0.5  1.204791e+09  2.626341e+08  4.239987e+08
2022-03-31   0.5  1.204791e+09  2.626341e+08  4.239987e+08
2022-04-30   0.5  1.204791e+09  2.626341e+08  4.239987e+08
2022-05-31   0.5  1.204791e+09  2.626341e+08  4.239987e+08
2022-06-30   0.5  1.204791e+09  2.626341e+08  4.239987e+08
2022-07-31   0.5  1.204791e+09  2.626341e+08  4.239987e+08
2022-08-31   0.5  1.204791e+09  2.626341e+08  4.239987e+08
2022-09-30   0.5  1.204791e+09  2.626341e+08  4.239987e+08
2022-10-31   0.5  1.204791e+09  2.626341e+08  4.239987e+08
2022-11-30   0.5  1.204791e+09  2.626341e+08  4.239987e+08
2022-12-31   1.5  1.261684e+09  2.935988e+08  4.570359e+08
2023-01-31   1.5  1.261684e+09  2.935988e+08  4.570359e+08
2023-02-28   1.5  1.261684e+09  2.935988e+08  4.570359e+08
2023-03-31   1.5  1.261684e+09  2.935988e+08  4.570359e+08
2023-04-30   1.5  1.261684e+09  2.935988e+08  4.570359e+08
2023-05-31   1.5  1.261684e+09  2.935988e+08  4.570359e+08
2023-06-30   1.5  1.261684e+09  2.935988e+08  4.570359e+08
2023-07-31   1.5  1.261684e+09  2.935988e+08  4.570359e+08

In [7]:
df2 = pd.read_excel("monthly_data_new.xlsx", usecols=[0,1,2,3,4], na_values=[""],index_col=0)
#dataset.set_index('Year')
IBT = df2['IBT']
df2

                 Time    Retirement       Pension           IBT
date
2021-10-31   0.083333  9.387313e+07  1.938965e+07  3.107564e+07
2021-11-30   0.166667  9.387313e+07  1.938965e+07  3.107564e+07
2021-12-31   0.250000  9.387313e+07  1.938965e+07  3.107564e+07
2022-01-31   0.333333  1.003993e+08  2.188617e+07  3.533322e+07
2022-02-28   0.416667  1.003993e+08  2.188617e+07  3.533322e+07
...               ...           ...           ...           ...
2100-09-30  79.000000  9.606686e+03  1.315861e+05  4.997286e+04
2100-10-31  79.083333  9.606686e+03  1.315861e+05  4.997286e+04
2100-11-30  79.166667  9.606686e+03  1.315861e+05  4.997286e+04
2100-12-31  79.250000  9.606686e+03  1.315861e+05  4.997286e+04
2101-01-31  79.333333  8.665401e+03  9.348450e+04  3.460866e+04

[952 rows x 4 columns]

In [8]:
df3 = pd.read_excel("UPS Pension - Historical Liability Data.xlsx",sheet_name = "IBT",skiprows = [0,1,2,3],usecols=[1,2], na_values=[""],index_col=0)
#dataset.set_index('Year')
df3 = df3.sort_index(ascending=False)
df3

                 IRR
Date
2021-07-31  0.027088
2021-06-30  0.028554
2021-05-31  0.030762
2021-04-30  0.031131
2021-03-31  0.032510
...              ...
2010-04-30  0.057504
2010-03-31  0.060101
2010-02-28  0.059820
2010-01-31  0.058975
2009-12-31  0.059959

[140 rows x 1 columns]

In [9]:
Time_CF = df2.index
Time_DR = df3.index
len(Time_CF)
IBT_DR = df3['IRR']
IBT_DR
DF = df2['Time']
len(DF)

952

In [10]:
liabilityIBT = ((IBT[7]/((1+IBT_DR[0])**DF[0])))
liabilityIBT

35254612.842204496

In [11]:
liabilityIBT = np.zeros(len(Time_DR))
for j in range (0,len(Time_DR)):
    for i in range (0,len(Time_CF)):
        liabilityIBT[j] += ((IBT[i]/((1+IBT_DR[j])**DF[i]))) 
liabilityIBT

array([1.57417816e+10, 1.53212114e+10, 1.47187073e+10, 1.46217479e+10,
       1.42671925e+10, 1.48580931e+10, 1.55549936e+10, 1.60588499e+10,
       1.60061912e+10, 1.52430168e+10, 1.56875272e+10, 1.57660260e+10,
       1.66845140e+10, 1.54837101e+10, 1.51828914e+10, 1.48596087e+10,
       1.37893558e+10, 1.55168248e+10, 1.50774992e+10, 1.41755154e+10,
       1.44746599e+10, 1.44706085e+10, 1.44694214e+10, 1.48357866e+10,
       1.37460429e+10, 1.35728813e+10, 1.32018376e+10, 1.27156839e+10,
       1.28760850e+10, 1.22659447e+10, 1.23116825e+10, 1.20909067e+10,
       1.16796245e+10, 1.16979502e+10, 1.21461448e+10, 1.23939411e+10,
       1.22856083e+10, 1.22555406e+10, 1.25138100e+10, 1.24172441e+10,
       1.26551281e+10, 1.25520209e+10, 1.29994222e+10, 1.34377369e+10,
       1.30777278e+10, 1.30520825e+10, 1.29794205e+10, 1.31434344e+10,
       1.28991141e+10, 1.28719899e+10, 1.27912288e+10, 1.25247739e+10,
       1.23753641e+10, 1.25356932e+10, 1.22913241e+10, 1.23142553e+10,
       1.23082372e+10, 1.30434374e+10, 1.34885566e+10, 1.37220949e+10,
       1.36542867e+10, 1.33674785e+10, 1.28897347e+10, 1.29428462e+10,
       1.26816772e+10, 1.22264443e+10, 1.19611201e+10, 1.19376173e+10,
       1.20270404e+10, 1.20287942e+10, 1.19633271e+10, 1.19152066e+10,
       1.20801614e+10, 1.18484256e+10, 1.24101995e+10, 1.27299578e+10,
       1.31343427e+10, 1.30991178e+10, 1.37022548e+10, 1.27217971e+10,
       1.25116386e+10, 1.22780556e+10, 1.20733313e+10, 1.24918778e+10,
       1.20680286e+10, 1.20765841e+10, 1.20951074e+10, 1.18574817e+10,
       1.16675468e+10, 1.15971597e+10, 1.14312761e+10, 1.09533609e+10,
       1.10278015e+10, 1.12151338e+10, 1.10035188e+10, 1.10718694e+10,
       1.11325889e+10, 1.11144060e+10, 1.16919306e+10, 1.25086580e+10,
       1.20283597e+10, 1.21517371e+10, 1.20454800e+10, 1.25407661e+10,
       1.28048406e+10, 1.29644103e+10, 1.27119687e+10, 1.28834870e+10,
       1.30105628e+10, 1.22349737e+10, 1.17581639e+10, 1.14341247e+10,
       1.12114178e+10, 1.15329407e+10, 1.14824835e+10, 1.15061017e+10,
       1.10204328e+10, 1.09699870e+10, 1.09062177e+10, 1.03539345e+10,
       1.01947065e+10, 9.83579907e+09, 1.01100236e+10, 9.94852305e+09,
       9.70762421e+09, 9.84778344e+09, 9.65217195e+09, 9.96091844e+09,
       1.00525102e+10, 1.01387245e+10, 1.05083114e+10, 1.06079164e+10,
       1.00908218e+10, 9.93155311e+09, 9.46050351e+09, 9.61590533e+09,
       9.27523915e+09, 9.31104495e+09, 9.42045483e+09, 9.29336565e+09])

In [12]:
IBT_Return = np.zeros(len(Time_DR)-1)
#for j in range (0,len(Time_DR)):
for i in range (0,len(Time_DR)-1):
        IBT_Return[i] = ((liabilityIBT[i+1]+IBT[i])/liabilityIBT[i])-1
IBT_Return

array([-2.47427294e-02, -3.72965592e-02, -4.47618813e-03, -2.18320162e-02,
        4.38932804e-02,  4.92818078e-02,  3.46634406e-02, -1.07887978e-03,
       -4.54724754e-02,  3.14795678e-02,  7.25621817e-03,  6.04985164e-02,
       -6.98534383e-02, -1.71461181e-02, -1.89653860e-02, -6.94612268e-02,
        1.28037551e-01, -2.58583352e-02, -5.72971356e-02,  2.37896715e-02,
        2.35134381e-03,  2.54994343e-03,  2.79521527e-02, -7.08865244e-02,
       -9.82648366e-03, -2.45310719e-02, -3.39397733e-02,  1.58149612e-02,
       -4.42248811e-02,  7.04673715e-03, -1.46266601e-02, -3.06499104e-02,
        5.05347394e-03,  4.17929305e-02,  2.37518458e-02, -5.45716773e-03,
        8.65181843e-04,  2.43943901e-02, -4.46458175e-03,  2.26259252e-02,
       -4.74429496e-03,  3.90748964e-02,  3.70310509e-02, -2.35859310e-02,
        1.33221020e-03, -2.26741147e-03,  1.59545982e-02, -1.53120349e-02,
        1.23600854e-03, -2.92833596e-03, -1.74641063e-02, -8.33029966e-03,
        1.65977891e-02, -1.58981645e-02,  5.53283268e-03,  3.17165182e-03,
        6.33945204e-02,  3.75816463e-02,  2.06554999e-02, -1.65671205e-03,
       -1.77038568e-02, -3.23673010e-02,  7.61738863e-03, -1.65527663e-02,
       -3.21963527e-02, -1.78625195e-02,  1.95853788e-03,  1.14220573e-02,
        4.04778483e-03, -1.54113089e-03, -9.95914566e-05,  1.77826476e-02,
       -1.52983636e-02,  5.13741678e-02,  2.95472618e-02,  3.55843833e-02,
        1.01854354e-03,  4.97544873e-02, -6.80074150e-02, -1.26991203e-02,
       -1.47846529e-02, -1.27154871e-02,  3.86926593e-02, -3.00392348e-02,
        4.73634987e-03,  5.55836819e-03, -1.56280458e-02, -1.18005320e-02,
       -1.74645565e-03, -9.99152567e-03, -3.74328208e-02,  1.13618931e-02,
        2.15221999e-02, -1.44095202e-02,  1.07566388e-02,  1.00010087e-02,
        2.85893756e-03,  5.64613998e-02,  7.41312715e-02, -3.43050225e-02,
        1.45128581e-02, -4.53174966e-03,  4.53676030e-02,  2.51390597e-02,
        1.64592555e-02, -1.55235074e-02,  1.75194618e-02,  1.38366527e-02,
       -5.56778845e-02, -3.47872724e-02, -2.32052099e-02, -1.49135754e-02,
        3.33326379e-02,  1.49657568e-04,  6.60148115e-03, -3.76744227e-02,
        1.57653459e-04, -1.05616331e-03, -4.58545727e-02, -1.03385670e-02,
       -3.00866123e-02,  3.31856866e-02, -1.08127685e-02, -1.88788611e-02,
        1.99061368e-02, -1.44732500e-02,  3.74867498e-02,  1.45241424e-02,
        1.38568768e-02,  4.16885756e-02,  1.45301169e-02, -4.37420940e-02,
       -1.05230935e-02, -4.20848123e-02,  2.20372925e-02, -2.98266675e-02,
        9.66676512e-03,  1.75346212e-02, -7.77387284e-03])

In [13]:
IBT_Returns = pd.DataFrame(IBT_Return)

#export monthly dataframe to excel
filepath = 'IBT Liability Returns.xlsx'
writer = pd.ExcelWriter(filepath, engine='xlsxwriter')
IBT_Returns.to_excel(writer, sheet_name='data')
writer.save()